# Generated by Django 3.2.6 on 2021-08-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Imageapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageUplaod',
            new_name='ImageUpload',
        ),
    ]
